vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        profile_images:
            uri_prefix: /images/profile
            upload_destination: '%kernel.project_dir%/public/images/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        programme_images:
            uri_prefix: /images/programme
            upload_destination: '%kernel.project_dir%/public/images/programme'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        seance_images:
            uri_prefix: /images/seance
            upload_destination: '%kernel.project_dir%/public/images/seance'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer    
